package com.example.spotifymood.ui;

import android.os.Bundle;
import android.os.Handler; // Needed for posting back to main thread
import android.os.Looper; // Needed for main thread handler
import android.util.Log; // For logging
import android.view.View;
import android.widget.TextView;
import android.widget.Toast; // For user feedback
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import com.example.spotifymood.R;
import com.example.spotifymood.adapter.RecommendationAdapter;
import com.example.spotifymood.model.Song;
import com.example.spotifymood.network.PlaylistDto; // Needed for createPlaylist response
import com.example.spotifymood.repository.PlaylistRepository; // Import repository
import com.google.android.material.floatingactionbutton.FloatingActionButton; // Import FAB

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executor; // Needed for background thread
import java.util.concurrent.Executors; // Needed for background thread
import java.util.stream.Collectors; // Needed for streams

public class RecommendationsActivity extends AppCompatActivity {

    private static final String TAG = "RecommendationsActivity";

    private RecyclerView recommendationsRecyclerView;
    private RecommendationAdapter adapter;
    private TextView recommendationHeader;
    private FloatingActionButton fabCreatePlaylist;
    private PlaylistRepository playlistRepository;
    private ArrayList<Song> recommendations;
    private String originalSongName;

    private final Executor backgroundExecutor = Executors.newSingleThreadExecutor();
    private final Handler mainThreadHandler = new Handler(Looper.getMainLooper());

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recommendations);

        playlistRepository = new PlaylistRepository();


        recommendationsRecyclerView = findViewById(R.id.recommendationsRecyclerView);
        recommendationHeader = findViewById(R.id.recommendationHeader);
        fabCreatePlaylist = findViewById(R.id.fabCreatePlaylist);


        originalSongName = getIntent().getStringExtra("originalSongName");
        Serializable recommendationsSerializable = getIntent().getSerializableExtra("recommendations");

        if (recommendationsSerializable instanceof ArrayList) {

            recommendations = (ArrayList<Song>) recommendationsSerializable;
        } else {
            Log.e(TAG, "Failed to retrieve recommendations list or it was the wrong type.");
            Toast.makeText(this, "Error: Could not load recommendations.", Toast.LENGTH_SHORT).show();

            recommendations = new ArrayList<>();

        }


        if (originalSongName != null) {
            recommendationHeader.setText("Songs similar to: " + originalSongName);
        } else {
            recommendationHeader.setText("Similar Songs Found:");
        }


        if (recommendations != null && !recommendations.isEmpty()) {

            adapter = new RecommendationAdapter(recommendations);
            recommendationsRecyclerView.setLayoutManager(new LinearLayoutManager(this));
            recommendationsRecyclerView.setAdapter(adapter);


            setupFabClickListener();

        } else {

            Log.w(TAG, "Recommendations list is null or empty.");
            recommendationHeader.setText("No recommendations found.");
            recommendationsRecyclerView.setVisibility(View.GONE);
            fabCreatePlaylist.setVisibility(View.GONE);
        }
    }


    private void setupFabClickListener() {
        fabCreatePlaylist.setOnClickListener(v -> {
            if (recommendations == null || recommendations.isEmpty()) {
                Toast.makeText(this, "No recommendations to add.", Toast.LENGTH_SHORT).show();
                return;
            }
            if (originalSongName == null) {
                originalSongName = "ClassiFy Mix";
            }

            String playlistName = "Mix - " + originalSongName;
            String playlistDescription = "Playlist generated by ClassiFy based on songs similar to " + originalSongName;

            Toast.makeText(this, "Creating playlist '" + playlistName + "'...", Toast.LENGTH_SHORT).show();


            backgroundExecutor.execute(() -> {

                PlaylistDto newPlaylist = playlistRepository.createSpotifyPlaylist(this, playlistName, playlistDescription);

                if (newPlaylist != null && newPlaylist.id != null) {

                    List<String> trackUris = recommendations.stream()
                            .map(Song::getTrackUri)
                            .collect(Collectors.toList());


                    boolean addedSuccessfully = playlistRepository.addTracksToSpotifyPlaylist(this, newPlaylist.id, trackUris);


                    mainThreadHandler.post(() -> {
                        if (addedSuccessfully) {
                            Toast.makeText(this, "Playlist created and songs added!", Toast.LENGTH_LONG).show();
                        } else {
                            Toast.makeText(this, "Playlist created, but failed to add songs.", Toast.LENGTH_LONG).show();
                        }
                    });
                } else {

                    mainThreadHandler.post(() -> {
                        Toast.makeText(this, "Failed to create playlist.", Toast.LENGTH_LONG).show();
                    });
                }
            });
        });
    }
}

